//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicUO.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGeneral() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicUO.Resources.ResGeneral", typeof(ResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   %1, a conference moderator, has kicked you out of the conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AConferenceModeratorKickedYou {
            get {
                return ResourceManager.GetString("AConferenceModeratorKickedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A fierce storm approaches. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AFierceStormApproaches {
            get {
                return ResourceManager.GetString("AFierceStormApproaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Alliance][{0}] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Alliance0 {
            get {
                return ResourceManager.GetString("Alliance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always run is now off. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlwaysRunIsNowOff {
            get {
                return ResourceManager.GetString("AlwaysRunIsNowOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always run is now on. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlwaysRunIsNowOn {
            get {
                return ResourceManager.GetString("AlwaysRunIsNowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A storm is brewing. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AStormIsBrewing {
            get {
                return ResourceManager.GetString("AStormIsBrewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backpack benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Backpack {
            get {
                return ResourceManager.GetString("Backpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1, a conference moderator, has banned you from the conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BannedYouFromTheConference {
            get {
                return ResourceManager.GetString("BannedYouFromTheConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Bard {
            get {
                return ResourceManager.GetString("Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bat Wing benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatWing {
            get {
                return ResourceManager.GetString("BatWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black Pearl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BlackPearl {
            get {
                return ResourceManager.GetString("BlackPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bloodmoss benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Bloodmoss {
            get {
                return ResourceManager.GetString("Bloodmoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot delete this group. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CannotDeleteThisGroup {
            get {
                return ResourceManager.GetString("CannotDeleteThisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check your internet connection and try again benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CheckYourConnectionAndTryAgain {
            get {
                return ResourceManager.GetString("CheckYourConnectionAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://uo.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClassicUOLink {
            get {
                return ResourceManager.GetString("ClassicUOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientViewRange is now {0}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClientViewRangeIsNow0 {
            get {
                return ResourceManager.GetString("ClientViewRangeIsNow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conference %1 renamed to %2. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Conference1RenamedTo2 {
            get {
                return ResourceManager.GetString("Conference1RenamedTo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection lost:
        ///{0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConnectionLost0 {
            get {
                return ResourceManager.GetString("ConnectionLost0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crafted by  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CraftedBy {
            get {
                return ResourceManager.GetString("CraftedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating character... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreatingCharacter {
            get {
                return ResourceManager.GetString("CreatingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current DateTime.Now is {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentDateTimeNowIs0 {
            get {
                return ResourceManager.GetString("CurrentDateTimeNowIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Czech benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daemon Blood benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DaemonBlood {
            get {
                return ResourceManager.GetString("DaemonBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   decreased benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Decreased {
            get {
                return ResourceManager.GetString("Decreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dexterity benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmoteChar {
            get {
                return ResourceManager.GetString("EmoteChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entering Britannia... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EnteringBritannia {
            get {
                return ResourceManager.GetString("EnteringBritannia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From now on, everyone in the conference will have speaking privileges by default. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EveryoneWillHaveSpeakingPrivs {
            get {
                return ResourceManager.GetString("EveryoneWillHaveSpeakingPrivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Garlic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Garlic {
            get {
                return ResourceManager.GetString("Garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ginseng benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ginseng {
            get {
                return ResourceManager.GetString("Ginseng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab Bag not found, setting to Backpack. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrabBagNotFound {
            get {
                return ResourceManager.GetString("GrabBagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab Bag set: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrabBagSet0 {
            get {
                return ResourceManager.GetString("GrabBagSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1, a conference moderator, has granted you speaking privileges in this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GrantedYouSpeakingPrivileges {
            get {
                return ResourceManager.GetString("GrantedYouSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grave Dust benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GraveDust {
            get {
                return ResourceManager.GetString("GraveDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Guild][{0}] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Guild0 {
            get {
                return ResourceManager.GetString("Guild0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 has been kicked out of the conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasBeenKickedOutOfTheConference {
            get {
                return ResourceManager.GetString("HasBeenKickedOutOfTheConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 has chosen to ignore you. None of your messages to them will get through. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasChosenToIgnoreYou {
            get {
                return ResourceManager.GetString("HasChosenToIgnoreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 has chosen to not receive private messages at the moment. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasChosenToNotReceivePM {
            get {
                return ResourceManager.GetString("HasChosenToNotReceivePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 has made you a conference moderator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasMadeYouAConferenceModerator {
            get {
                return ResourceManager.GetString("HasMadeYouAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 has removed you from the list of conference moderators. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasRemovedYouFromModerators {
            get {
                return ResourceManager.GetString("HasRemovedYouFromModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hits benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   increased benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Increased {
            get {
                return ResourceManager.GetString("Increased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   intelligence benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invariant benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Invariant {
            get {
                return ResourceManager.GetString("Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 is known in the lands of Britannia as %2. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IsKnownInTheLandsOfBritanniaAs2 {
            get {
                return ResourceManager.GetString("IsKnownInTheLandsOfBritanniaAs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 is no longer a conference moderator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IsNoLongerAConferenceModerator {
            get {
                return ResourceManager.GetString("IsNoLongerAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 is now a conference moderator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IsNowAConferenceModerator {
            get {
                return ResourceManager.GetString("IsNowAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 is remaining anonymous. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IsRemainingAnonymous {
            get {
                return ResourceManager.GetString("IsRemainingAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It begins to rain. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ItBeginsToRain {
            get {
                return ResourceManager.GetString("ItBeginsToRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It begins to snow. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ItBeginsToSnow {
            get {
                return ResourceManager.GetString("ItBeginsToSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item ID: {0}
        ///Hue: {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ItemID0Hue1 {
            get {
                return ResourceManager.GetString("ItemID0Hue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging into Shard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoggingIntoShard {
            get {
                return ResourceManager.GetString("LoggingIntoShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mana benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mandrake Root benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MandrakeRoot {
            get {
                return ResourceManager.GetString("MandrakeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From now on, only moderators will have speaking privileges in this conference by default. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ModeratorsWillHaveSpeakingPrivs {
            get {
                return ResourceManager.GetString("ModeratorsWillHaveSpeakingPrivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: {0} - {1:F1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Name0Val1 {
            get {
                return ResourceManager.GetString("Name0Val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nightshade benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Nightshade {
            get {
                return ResourceManager.GetString("Nightshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 no longer has speaking privileges in this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoLongerHasSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NoLongerHasSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The moderator of this conference has not given you speaking privileges. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotGivenYouSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NotGivenYouSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;not seeing&gt; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotSeeing {
            get {
                return ResourceManager.GetString("NotSeeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now following. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NowFollowing {
            get {
                return ResourceManager.GetString("NowFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 now has speaking privileges in this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NowHasSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NowHasSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nox Crystal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoxCrystal {
            get {
                return ResourceManager.GetString("NoxCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ouch! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ouch {
            get {
                return ResourceManager.GetString("Ouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paperdoll benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Paperdoll {
            get {
                return ResourceManager.GetString("Paperdoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Party][{0}] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Party0 {
            get {
                return ResourceManager.GetString("Party0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password to the conference has been changed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordToTheConferenceChanged {
            get {
                return ResourceManager.GetString("PasswordToTheConferenceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pathfinding! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pathfinding {
            get {
                return ResourceManager.GetString("Pathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pig Iron benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PigIron {
            get {
                return ResourceManager.GetString("PigIron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit
        ///Ultima Online? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string QuitPrompt {
            get {
                return ResourceManager.GetString("QuitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reconnect, please wait...`{0}`
        ///`{1}` benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReconnectPleaseWait01 {
            get {
                return ResourceManager.GetString("ReconnectPleaseWait01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1, a conference moderator, has removed your speaking privileges for this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RemovedYourSpeakingPrivileges {
            get {
                return ResourceManager.GetString("RemovedYourSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salute benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Salute {
            get {
                return ResourceManager.GetString("Salute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot stored in: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScreenshotStoredIn0 {
            get {
                return ResourceManager.GetString("ScreenshotStoredIn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spiders Silk benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SpidersSilk {
            get {
                return ResourceManager.GetString("SpidersSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Stam {
            get {
                return ResourceManager.GetString("Stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped following. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StoppedFollowing {
            get {
                return ResourceManager.GetString("StoppedFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   strength benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sulfurous Ash benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SulfurousAsh {
            get {
                return ResourceManager.GetString("SulfurousAsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Target0 {
            get {
                return ResourceManager.GetString("Target0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target an Item to grab it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TargetAnItemToGrabIt {
            get {
                return ResourceManager.GetString("TargetAnItemToGrabIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [WARN] - TargetSystem On/Off not implemented benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TargetSystemNotImplemented {
            get {
                return ResourceManager.GetString("TargetSystemNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kanal adi gecerli degil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThatIsNotAValidConferenceName {
            get {
                return ResourceManager.GetString("ThatIsNotAValidConferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kanal sifresi yanlis. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThatIsNotTheCorrectPassword {
            get {
                return ResourceManager.GetString("ThatIsNotTheCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry--the conference named &apos;%1&apos; is full and no more players are allowed in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TheConferenceNamed1IsFull {
            get {
                return ResourceManager.GetString("TheConferenceNamed1IsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu isimde zaten bir sohbet kanali var. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThereIsAlreadyAConference {
            get {
                return ResourceManager.GetString("ThereIsAlreadyAConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;%1&apos; isimli sohbet kanali bulunamadi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThereIsNoConferenceNamed1 {
            get {
                return ResourceManager.GetString("ThereIsNoConferenceNamed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no player named &apos;%1&apos;. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThereIsNoPlayerNamed1 {
            get {
                return ResourceManager.GetString("ThereIsNoPlayerNamed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thieving benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Thieving {
            get {
                return ResourceManager.GetString("Thieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This may flag
        ///you criminal! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThisMayFlagYouCriminal {
            get {
                return ResourceManager.GetString("ThisMayFlagYouCriminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trade Skills benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TradeSkills {
            get {
                return ResourceManager.GetString("TradeSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying Account... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weight benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wilderness benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Wilderness {
            get {
                return ResourceManager.GetString("Wilderness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClassicUO - {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WindowTitle0 {
            get {
                return ResourceManager.GetString("WindowTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are already ignoring %1. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreAlreadyIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreAlreadyIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are already ignoring the maximum number of people. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreAlreadyIgnoringMaximum {
            get {
                return ResourceManager.GetString("YouAreAlreadyIgnoringMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaten &apos;%1&apos; sohbet kanalindasiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreAlreadyInTheConference1 {
            get {
                return ResourceManager.GetString("YouAreAlreadyInTheConference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are banning %1 from this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreBanning1FromThisConference {
            get {
                return ResourceManager.GetString("YouAreBanning1FromThisConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are dead. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreDead {
            get {
                return ResourceManager.GetString("YouAreDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are no longer ignoring %1. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreNoLongerIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNoLongerIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are no longer ignoring anyone. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreNoLongerIgnoringAnyone {
            get {
                return ResourceManager.GetString("YouAreNoLongerIgnoringAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not ignoring %1. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreNotIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNotIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are no longer showing your character name to any players who inquire with the whois command. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreNotShowingYourCharName {
            get {
                return ResourceManager.GetString("YouAreNotShowingYourCharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are now ignoring %1. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreNowIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNowIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are now showing your character name to any players who inquire with the whois command. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouAreShowingYourCharName {
            get {
                return ResourceManager.GetString("YouAreShowingYourCharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can now receive private messages. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouCanNowReceivePM {
            get {
                return ResourceManager.GetString("YouCanNowReceivePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have been banned from this conference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouHaveBeenBanned {
            get {
                return ResourceManager.GetString("YouHaveBeenBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; sohbet kanalina katildiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouHaveJoinedThe0Channel {
            get {
                return ResourceManager.GetString("YouHaveJoinedThe0Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; sohbet kanalindan ayrildiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouHaveLeftThe0Channel {
            get {
                return ResourceManager.GetString("YouHaveLeftThe0Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herhangi bir sohbet kanalinda degilsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouMustBeInAConference {
            get {
                return ResourceManager.GetString("YouMustBeInAConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must have operator status to do this. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouMustHaveOperatorStatus {
            get {
                return ResourceManager.GetString("YouMustHaveOperatorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your {0} has changed by {1}.  It is now {2} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Your0HasChangedBy1ItIsNow2 {
            get {
                return ResourceManager.GetString("Your0HasChangedBy1ItIsNow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your skill in {0} has {1} by {2:F1}.  It is now {3:F1}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourSkillIn0Has1By2ItIsNow3 {
            get {
                return ResourceManager.GetString("YourSkillIn0Has1By2ItIsNow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ultima Online istemci sürümünüz geçersiz görünüyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourUOClientVersionIsInvalid {
            get {
                return ResourceManager.GetString("YourUOClientVersionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ultima Online dizininiz geçersiz görünüyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourUODirectoryIsInvalid {
            get {
                return ResourceManager.GetString("YourUODirectoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You see benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouSee {
            get {
                return ResourceManager.GetString("YouSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will no longer receive private messages. Those who send you a message will be notified that you are blocking incoming messages. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YouWillNoLongerReceivePM {
            get {
                return ResourceManager.GetString("YouWillNoLongerReceivePM", resourceCulture);
            }
        }
    }
}
